# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HousingForUCMStudents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HousingForUCMStudents
  pod 'AlamofireImage'
  pod 'Parse'
  
  target 'HousingForUCMStudentsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HousingForUCMStudentsUITests' do
    # Pods for testing
  end

end
